packages:
- .
extra-deps:
- git: https://github.com/facebook/duckling.git
  commit: a93cae1c02c28c51e5bce1f03132a211bbda7dce
- git: https://github.com/andfoy/curryrs.git
  commit: 44da82c04036474802f4c1358d04e91adc40d1d9
  subdirs:
    - haskell
resolver: lts-14.1
allow-newer: true
